version: '3.1'
services:
  mysql:
    image: mariadb:10.11
    restart: always
    volumes:
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:7.0.3
    ports:
    - 80:80
    - 443:443
    command: sh -c "./openemr.sh; mysql -u root -proot -e 'source /tmp/sql/patient_data.sql'"
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    - ./sql:/tmp/sql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
    - mysql
volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}