version: '3.1'
services:
  mysql:
    image: mariadb
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemr
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - databasevolume:/var/lib/mysql
  openemr:
    restart: always
    image: openemr/openemr:7.0.0
    ports:
    - 80:80
    - 443:443
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
    - mysql
volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}